#platform
platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'NTESQuickPassPublicDemo' do
  pod 'Masonry', '~> 1.0.2'
  pod 'NTESQuickPass', :path => '../../NTESQuickPass.podspec'
end
